// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a6d07620-0f94-4ec8-9047-da6f9460da75";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedChange();
void onStartStopChange();
void onDiffChange();
void onKpChange();
void onPowerChange();

bool led;
bool startStop;
float diff;
float kp;
int power;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(startStop, READWRITE, ON_CHANGE, onStartStopChange);
  ArduinoCloud.addProperty(diff, READWRITE, ON_CHANGE, onDiffChange);
  ArduinoCloud.addProperty(kp, READWRITE, ON_CHANGE, onKpChange);
  ArduinoCloud.addProperty(power, READWRITE, ON_CHANGE, onPowerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
